version: '2'


services:
        es:
                image: elasticsearch:7.7.0
                container_name: sockyjam.es
                ports:
                        - "9200:9200"
                        - "9300:9300"
                environment:
                        - discovery.type=single-node

