version: '2'

services:


    es01:
        build: elasticsearch
        image: sockyjam/elasticsearch:v01
        container_name: sockyjam.es01
        environment:
            - node.name=es01
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./es_data01:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - elastic




networks:
    elastic:
        driver: bridge
