FROM elasticsearch:7.7.0
MAINTAINER SockyJam <sockyjam@126.com>

#RUN ./bin/elasticsearch-plugin install  https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.7.0/elasticsearch-analysis-ik-7.7.0.zip



